name = "PiADXL345"
uuid = "0ca55b5e-7d6a-48ea-ae42-ee7e45b974f2"
authors = ["notinaboat <notinaboat@icloud.com>"]
version = "0.1.0"

[deps]
BBSPI = "d9c4ebee-6e29-4c04-a492-1c21dbbc648c"
PiGPIOMEM = "1cdbf0ad-f496-4de0-97e4-602941adc73e"
